#!/bin/bash

CONFIG=$HOME/.config/keepass/keepass.localconfig.xml
CONFIGDIR=$(dirname ${CONFIG})
CONTAINERNAME=keepass

if [ ! -e $CONFIG ] ; then
	cat <<- _END_ > $CONFIG 
	<?xml version="1.0" encoding="utf-8"?>
	<Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">
		<Security>
			<WorkspaceLocking>
				<LockOnWindowMinimize>true</LockOnWindowMinimize>
			</WorkspaceLocking>
		</Security>
	</Configuration>
	_END_
fi

if [[ $(docker inspect keepass --format "{{.State.Status}}" 2> /dev/null) == 'running' ]] ; then
	echo 'already running' ;
	docker exec $CONTAINERNAME mono /keepass/KeePass.exe $@
else
	docker run \
		-v /tmp/.X11-unix:/tmp/.X11-unix \
		-e DISPLAY=unix$DISPLAY \
		-d \
		-v $XAUTHORITY:/keepass/.Xauthority:ro \
		-e XAUTHORITY="/keepass/.Xauthority" \
		-h $HOSTNAME \
		-v ${CONFIGDIR}:/config \
		-v $HOME/dropbox:/data \
		-u $(id -u) \
		--rm \
		--name $CONTAINERNAME \
		keepass
fi
