#!/bin/bash

case ${reason} in
	pre-init)
		DEFAULT_ROUTE=$(ip route | grep ^default)
		NS=$(grep nameserver /etc/resolv.conf)
		;;

	connect)
		echo VPNGATEWAY ${VPNGATEWAY}
		echo INTERNAL_IP4_ADDRESS ${INTERNAL_IP4_ADDRESS}
		echo TUNDEV ${TUNDEV}
		echo DEFAULT_ROUTE ${DEFAULT_ROUTE}
		#ip route add 10.0.0.0/8 via ${VPNGATEWAY} dev ${TUNDEV}
		#ip route add ${DEFAULT_ROUTE}

		# need to do this via NetworkManager anyway
		cat <<- EOF > /etc/resolv.conf 
			nameserver $(echo ${INTERNAL_IP4_DNS} | sed -e 's/ /\n/')
			nameserver ${NS}
		EOF

		;;

	disconnect)


		;;

esac

# remove the automatically added default route
#ip route del $(ip route | grep default)
