#!/bin/bash

case ${reason} in
	connect)
		ip addr add ${INTERNAL_IP4_ADDRESS} dev ${TUNDEV}
		ip link set ${TUNDEV} up
		ip route add 10.0.0.0/8 via ${INTERNAL_IP4_ADDRESS} dev ${TUNDEV}
		iptables -t nat -A POSTROUTING -d 10.0.0.0/8 -j SNAT --to-source ${INTERNAL_IP4_ADDRESS}

		echo Remote nameservers are ${INTERNAL_IP4_DNS}
		echo ip route 10.0.0.0/8 via $(ip addr | awk '/inet.*eth0/ { print $2 }' | cut -d/ -f1)
		;;

	disconnect)


		;;

esac
