#!/bin/bash

ADBGROUP=$(getent group adbusers)

DOCKER_ARGS="-u $UID \
	--group-add kvm \
	-v /tmp/.X11-unix:/tmp/.X11-unix \
	-v $HOME/StudioProjects:/projects \
	-v $HOME/dropbox/Random:/keystore \
	-v $HOME/android-studio:/home \
	-e JAVA_HOME=/jdk/jre1.8.0_181 \
	-e DISPLAY=unix$DISPLAY \
	-e XAUTHORITY=/home/.Xauthority \
	-v /etc/timezone:/etc/timezone:ro \
	-v /etc/localtime:/etc/localtime:ro \
	-v $XAUTHORITY:/home/.Xauthority \
	-h $HOSTNAME \
	--name android-studio \
	--rm \
	-d"

if [[ -n $ADBGROUP ]]
then
	DOCKER_ARGS+=" --group-add $(getent group adbusers | cut -d: -f3)"
else
	echo "adbusers group missing"
fi

DEVNAMES="kvm dri"
if [[ -c /dev/android && -c /dev/android_adb ]]
then
	DEVNAMES+=" android android_adb bus/usb"
fi

for dev in $DEVNAMES
do
	DEVICES+="--device /dev/${dev}:/dev/${dev} "
done

docker run $DOCKER_ARGS $DEVICES android-studio:3.2.1
